//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_DBPersonel_Deneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public byte ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Şehir { get; set; }
        public Nullable<short> Maaş { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Yaş { get; set; }
    }
}
